spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    consumer:
      group-id: "tiltak-datadeling"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  application:
    name: tiltak-datadeling
  main:
    banner-mode: "off"
  graphql:
    path: '/graphql'
    graphiql:
      enabled: true
management:
  endpoints:
    web:
      base-path: /internal/
      exposure:
        include: info, health, metrics, prometheus

tiltak-datadeling:
  kafka:
    topic: arbeidsgiver.tiltak-avtale-hendelse-compact
  opensearch:
    index: avtale
    urlString: ${OPEN_SEARCH_URI}
    username: ${OPEN_SEARCH_USERNAME}
    password: ${OPEN_SEARCH_PASSWORD}