spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    consumer:
      group-id: "tiltak-datadeling-testing"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  application:
    name: tiltak-datadeling
  main:
    banner-mode: "off"
  graphql:
    path: '/graphql'
    #TODO deaktiver graphiql? Iallefall i prod?
    graphiql:
      enabled: true
      path: '/graphiql'
management:
  endpoints:
    web:
      base-path: /internal/
      exposure:
        include: info, health, metrics, prometheus
