apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltak-datadeling
  namespace: team-tiltak
  labels:
    team: team-tiltak
spec:
  env:
    - name: MILJO
      value: dev-gcp
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        cascadingDelete: false
        highAvailability: false
        diskAutoresize: true
        diskAutoresizeLimit: 60
        databases:
          - name: tiltak-datadeling
            envVarPrefix: DB
  kafka:
    pool: nav-dev
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  ingresses:
    - https://tiltak-datadeling.intern.dev.nav.no/
  strategy:
    type: RollingUpdate
  prometheus:
    enabled: true
    path: /internal/prometheus
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: wonderwalled-azure
          namespace: aura
          cluster: dev-gcp
        - application: tiltak-admin
          namespace: team-tiltak
          cluster: dev-gcp
        - application: tiltakshistorikk
          namespace: team-mulighetsrommet
