apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltak-datadeling
  namespace: teamtiltak
  labels:
    team: teamtiltak
spec:
  env:
    - name: MILJO
      value: dev-gcp
  kafka:
    pool: nav-dev
  image: {{image}}
  team: teamtiltak
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  ingresses:
    - https://tiltak-datadeling.intern.dev.nav.no/
  leaderElection: true
  vault:
    enabled: true
  strategy:
    type: RollingUpdate
  prometheus:
    enabled: true
    path: /internal/prometheus
