apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltak-datadeling
  namespace: team-tiltak
  labels:
    team: team-tiltak
spec:
  env:
    - name: MILJO
      value: prod-gcp
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        cascadingDelete: false
        highAvailability: true
        diskAutoresize: true
        diskAutoresizeLimit: 60
        databases:
          - name: tiltak-datadeling
            envVarPrefix: DB
  kafka:
    pool: nav-prod
  image: {{image}}
  port: 8080
  replicas:
    min: 2
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  ingresses:
    - https://tiltak-datadeling.intern.nav.no/
  strategy:
    type: RollingUpdate
  prometheus:
    enabled: true
    path: /internal/prometheus
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        # https://behandlingskatalog.intern.nav.no/process/team/aa730c95-b437-497b-b1ae-0ccf69a10997/435e06e3-7d06-4331-9b99-46cc9a6e58aa
        - application: tiltakshistorikk
          namespace: team-mulighetsrommet