name: Deploy opensearch

on:
  push:
    branches:
      - main
    paths:
      - '.nais/opensearch-dev.yaml'
      - '.github/workflows/deploy-opensearch.yaml'
  workflow_dispatch:

jobs:
  deploy-opensearch:
    name: Deploy opensearch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/opensearch-dev.yaml